-- This file allow to write SQL commands that will be emitted in test and dev.
CREATE TABLE IF NOT EXISTS PASSWD (USERNAME VARCHAR(255) NOT NULL PRIMARY KEY,ENCODEDPASSWORD VARCHAR(255) NOT NULL);

INSERT INTO PASSWD (USERNAME, ENCODEDPASSWORD) VALUES ('user1', 'sunshine');
INSERT INTO PASSWD (USERNAME, ENCODEDPASSWORD) VALUES ('user2', 'trainspotting');
INSERT INTO PASSWD (USERNAME, ENCODEDPASSWORD) VALUES ('user3', 'olympic');

